"""Revert embedding dimension to 768

Revision ID: 457fdd4c46b2
Revises: 61f4611b876a
Create Date: 2026-08-28 09:09:01.168697

"""
from collections.abc import Sequence

import pgvector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '457fdd4c46b2'
down_revision: str | Sequence[str] | None = '61f4611b876a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    # ### end Alembic commands ###
