"""Migrate to SQLAlchemy 2.0 Mapped syntax

Revision ID: 61f4611b876a
Revises: efb5ccf3685e
Create Date: 2026-08-28 08:44:31.787191

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '61f4611b876a'
down_revision: str | Sequence[str] | None = 'efb5ccf3685e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
