"""Initial migration

Revision ID: 976b780aaf43
Revises: 
Create Date: 2026-08-31 13:25:55.127313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '976b780aaf43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('class_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('class_level', sa.String(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('requested_topic', sa.String(), nullable=True),
    sa.Column('requested_difficulty', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('plan_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('marking_scheme', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('similar_to_source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['generation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_question_number', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.Enum('OBJECTIVE', 'NUMERICAL', 'SUBJECTIVE', name='questioncategory'), nullable=True),
    sa.Column('question_type', sa.Enum('MCQ', 'MULTIPLE_SELECT', 'TRUE_FALSE', 'FILL_IN_THE_BLANK', 'EXACT_ANSWER', 'NUMERIC', 'FORMULA', 'UNIT_BASED', 'SHORT_ANSWER', 'EXPLANATION', 'DESCRIPTIVE', 'ESSAY', 'PROOF', 'DERIVATION', name='questiontype'), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('generated_questions')
    op.drop_table('generation_requests')
    op.drop_table('documents')
    # ### end Alembic commands ###
