[project]
name = "ai-question-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "google-genai>=2.18.1",
    "greenlet>=3.5.5",
    "mypy>=2.3.1",
    "pgvector>=0.5.0",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "pymupdf>=1.28.2",
    "pytest>=9.1.1",
    "python-multipart>=0.0.32",
    "ruff>=0.16.3",
    "scalar-fastapi>=1.8.2",
    "sqlalchemy>=2.0.52",
    "tenacity>=9.1.4",
    "uvicorn>=0.52.3",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.4.0",
]
