"""Update Recommendation model

Revision ID: ed59577eb656
Revises: f12e33dbc04d
Create Date: 2026-08-28 14:07:40.907993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed59577eb656'
down_revision: Union[str, Sequence[str], None] = 'f12e33dbc04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraint first
    op.drop_constraint('recommendations_product_id_fkey', 'recommendations', type_='foreignkey')
    op.drop_table('product_embeddings')
    op.drop_index('ix_products_tenant_id', table_name='products')
    op.drop_table('products')
    op.add_column('recommendations', sa.Column('name', sa.String(), nullable=False))
    op.add_column('recommendations', sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('recommendations', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('recommendations_product_id_fkey'), 'recommendations', 'products', ['product_id'], ['id'])
    op.drop_column('recommendations', 'sources')
    op.drop_column('recommendations', 'name')
    op.create_table('products',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('stock_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('product_embeddings',
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('embedding_model_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_embeddings_product_id_fkey')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('product_embeddings_pkey'))
    )
    # ### end Alembic commands ###
